// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/task_manager/usecase/task_usecase.go

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskUsecase is a mock of TaskUsecase interface.
type MockTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUsecaseMockRecorder
}

// MockTaskUsecaseMockRecorder is the mock recorder for MockTaskUsecase.
type MockTaskUsecaseMockRecorder struct {
	mock *MockTaskUsecase
}

// NewMockTaskUsecase creates a new mock instance.
func NewMockTaskUsecase(ctrl *gomock.Controller) *MockTaskUsecase {
	mock := &MockTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUsecase) EXPECT() *MockTaskUsecaseMockRecorder {
	return m.recorder
}

// CreateDownloadLinkWithMdString mocks base method.
func (m *MockTaskUsecase) CreateDownloadLinkWithMdString(mdString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDownloadLinkWithMdString", mdString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDownloadLinkWithMdString indicates an expected call of CreateDownloadLinkWithMdString.
func (mr *MockTaskUsecaseMockRecorder) CreateDownloadLinkWithMdString(mdString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDownloadLinkWithMdString", reflect.TypeOf((*MockTaskUsecase)(nil).CreateDownloadLinkWithMdString), mdString)
}

// ProcessOCRAndTranslate mocks base method.
func (m *MockTaskUsecase) ProcessOCRAndTranslate(username string, fileContent []byte, lang string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOCRAndTranslate", username, fileContent, lang)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessOCRAndTranslate indicates an expected call of ProcessOCRAndTranslate.
func (mr *MockTaskUsecaseMockRecorder) ProcessOCRAndTranslate(username, fileContent, lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOCRAndTranslate", reflect.TypeOf((*MockTaskUsecase)(nil).ProcessOCRAndTranslate), username, fileContent, lang)
}
